export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';

export const GET_VENDOR_COUNT = 'GET_VENDOR_COUNT';
export const GET_USER_COUNT = 'GET_USER_COUNT';

export const POST_LOADING = 'POST_LOADING';
export const GET_POSTS = 'GET_POSTS';
export const GET_POST = 'GET_POST';
export const GET_POSTS_COUNT = 'GET_POSTS_COUNT';
export const GET_COMPLETED_POST_COUNT = 'GET_COMPLETED_POST_COUNT';
export const ADD_POST = 'ADD_POST';
export const DELETE_POST = 'DELETE_POST';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const CATEGORY_LOADING = 'CATEGORY_LOADING';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_PARENT_CATS = 'GET_PARENT_CATS';
export const GET_SUB_CATS = 'GET_SUB_CATS';
export const GET_SUB_CATS_LVL2 = 'GET_SUB_CATS_LVL2';
export const GET_CATEGORY = 'GET_CATEGORY';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const CLEAR_CATEGORY_ERRORS = 'CLEAR_CATEGORY_ERRORS';

export const BID_LOADING = 'BID_LOADING';
export const GET_BIDS = 'GET_BIDS';
export const GET_BID = 'GET_BID';
export const ADD_BID = 'ADD_BID';
export const DELETE_BID = 'DELETE_BID';
export const CLEAR_BID_ERRORS = 'CLEAR_BID_ERRORS';

export const PAYMENT_LOADING = 'PAYMENT_LOADING';
export const GET_PAYMENTS = 'GET_PAYMENTS';
export const GET_PAYMENT = 'GET_PAYMENT';
export const ADD_PAYMENT = 'ADD_PAYMENT';
export const DELETE_PAYMENT = 'DELETE_PAYMENT';
export const CLEAR_PAYMENT_ERRORS = 'CLEAR_PAYMENT_ERRORS';
